version: '3.2'

services:
  api:
    build: "bigvoto/"
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./bigvoto:/app
  voteservice:
    build: "voteService/"
    ports:
      - "8010:8010"
    restart: always
    depends_on:
      - api
    volumes:
      - ./voteService:/app

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"

    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres/data/:/var/lib/postgresql/data/
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  #bigvotofrontend:
  #  build: "bigvotoFrontend/"
  #  container_name: bigvotoFrontend
  #  volumes:
  #    - ./bigvotoFrontend:/src
  #  ports:
  #    - "3000:3000"
  #  restart: always
  #  depends_on:
  #    - api
