"""empty message

Revision ID: 777e3fbdf27c
Revises: 4b4f05424129
Create Date: 2022-03-31 22:08:07.804890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777e3fbdf27c'
down_revision = '4b4f05424129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
